/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TecnicoRouteImport } from './routes/tecnico'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListaTecnicosRouteImport } from './routes/lista-tecnicos'
import { Route as ListaClientesRouteImport } from './routes/lista-clientes'
import { Route as CadastroTecnicoRouteImport } from './routes/cadastro-tecnico'
import { Route as CadastroClienteRouteImport } from './routes/cadastro-cliente'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AtribuicaoTecnicosRouteImport } from './routes/atribuicao-tecnicos'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TecnicoIndexRouteImport } from './routes/tecnico.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as TecnicoPerfilRouteImport } from './routes/tecnico.perfil'
import { Route as TecnicoHistoricoRouteImport } from './routes/tecnico.historico'
import { Route as TecnicoAtendimentosRouteImport } from './routes/tecnico.atendimentos'
import { Route as TecnicoAgendaRouteImport } from './routes/tecnico.agenda'
import { Route as ListaClientesPendentesRouteImport } from './routes/lista-clientes.pendentes'
import { Route as ListaClientesIdRouteImport } from './routes/lista-clientes.$id'
import { Route as EtiquetaIdRouteImport } from './routes/etiqueta.$id'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppEquipamentosRouteImport } from './routes/app.equipamentos'
import { Route as AppChamadosRouteImport } from './routes/app.chamados'
import { Route as TecnicoAtendimentoIdRouteImport } from './routes/tecnico.atendimento.$id'
import { Route as AppEquipamentosNovoRouteImport } from './routes/app.equipamentos.novo'
import { Route as AppEquipamentosIdRouteImport } from './routes/app.equipamentos.$id'
import { Route as AppChamadosNovoRouteImport } from './routes/app.chamados.novo'
import { Route as AppChamadosIdRouteImport } from './routes/app.chamados.$id'
import { Route as TecnicoAtendimentoIdRegistroRouteImport } from './routes/tecnico.atendimento.$id.registro'
import { Route as TecnicoAtendimentoIdChecklistRouteImport } from './routes/tecnico.atendimento.$id.checklist'
import { Route as ListaClientesIdEquipamentosNovoRouteImport } from './routes/lista-clientes.$id.equipamentos.novo'
import { Route as ListaClientesIdEquipamentosEquipIdRouteImport } from './routes/lista-clientes.$id.equipamentos.$equipId'
import { Route as ListaClientesIdEquipamentosEquipIdFinalizarRouteImport } from './routes/lista-clientes.$id.equipamentos.$equipId.finalizar'

const TecnicoRoute = TecnicoRouteImport.update({
  id: '/tecnico',
  path: '/tecnico',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaTecnicosRoute = ListaTecnicosRouteImport.update({
  id: '/lista-tecnicos',
  path: '/lista-tecnicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaClientesRoute = ListaClientesRouteImport.update({
  id: '/lista-clientes',
  path: '/lista-clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroTecnicoRoute = CadastroTecnicoRouteImport.update({
  id: '/cadastro-tecnico',
  path: '/cadastro-tecnico',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroClienteRoute = CadastroClienteRouteImport.update({
  id: '/cadastro-cliente',
  path: '/cadastro-cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AtribuicaoTecnicosRoute = AtribuicaoTecnicosRouteImport.update({
  id: '/atribuicao-tecnicos',
  path: '/atribuicao-tecnicos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnicoIndexRoute = TecnicoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TecnicoRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const TecnicoPerfilRoute = TecnicoPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => TecnicoRoute,
} as any)
const TecnicoHistoricoRoute = TecnicoHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => TecnicoRoute,
} as any)
const TecnicoAtendimentosRoute = TecnicoAtendimentosRouteImport.update({
  id: '/atendimentos',
  path: '/atendimentos',
  getParentRoute: () => TecnicoRoute,
} as any)
const TecnicoAgendaRoute = TecnicoAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => TecnicoRoute,
} as any)
const ListaClientesPendentesRoute = ListaClientesPendentesRouteImport.update({
  id: '/pendentes',
  path: '/pendentes',
  getParentRoute: () => ListaClientesRoute,
} as any)
const ListaClientesIdRoute = ListaClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ListaClientesRoute,
} as any)
const EtiquetaIdRoute = EtiquetaIdRouteImport.update({
  id: '/etiqueta/$id',
  path: '/etiqueta/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipamentosRoute = AppEquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppChamadosRoute = AppChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => AppRoute,
} as any)
const TecnicoAtendimentoIdRoute = TecnicoAtendimentoIdRouteImport.update({
  id: '/atendimento/$id',
  path: '/atendimento/$id',
  getParentRoute: () => TecnicoRoute,
} as any)
const AppEquipamentosNovoRoute = AppEquipamentosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppEquipamentosRoute,
} as any)
const AppEquipamentosIdRoute = AppEquipamentosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEquipamentosRoute,
} as any)
const AppChamadosNovoRoute = AppChamadosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppChamadosRoute,
} as any)
const AppChamadosIdRoute = AppChamadosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppChamadosRoute,
} as any)
const TecnicoAtendimentoIdRegistroRoute =
  TecnicoAtendimentoIdRegistroRouteImport.update({
    id: '/registro',
    path: '/registro',
    getParentRoute: () => TecnicoAtendimentoIdRoute,
  } as any)
const TecnicoAtendimentoIdChecklistRoute =
  TecnicoAtendimentoIdChecklistRouteImport.update({
    id: '/checklist',
    path: '/checklist',
    getParentRoute: () => TecnicoAtendimentoIdRoute,
  } as any)
const ListaClientesIdEquipamentosNovoRoute =
  ListaClientesIdEquipamentosNovoRouteImport.update({
    id: '/equipamentos/novo',
    path: '/equipamentos/novo',
    getParentRoute: () => ListaClientesIdRoute,
  } as any)
const ListaClientesIdEquipamentosEquipIdRoute =
  ListaClientesIdEquipamentosEquipIdRouteImport.update({
    id: '/equipamentos/$equipId',
    path: '/equipamentos/$equipId',
    getParentRoute: () => ListaClientesIdRoute,
  } as any)
const ListaClientesIdEquipamentosEquipIdFinalizarRoute =
  ListaClientesIdEquipamentosEquipIdFinalizarRouteImport.update({
    id: '/finalizar',
    path: '/finalizar',
    getParentRoute: () => ListaClientesIdEquipamentosEquipIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/atribuicao-tecnicos': typeof AtribuicaoTecnicosRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-cliente': typeof CadastroClienteRoute
  '/cadastro-tecnico': typeof CadastroTecnicoRoute
  '/lista-clientes': typeof ListaClientesRouteWithChildren
  '/lista-tecnicos': typeof ListaTecnicosRoute
  '/login': typeof LoginRoute
  '/pagamento': typeof PagamentoRoute
  '/planos': typeof PlanosRoute
  '/tecnico': typeof TecnicoRouteWithChildren
  '/app/chamados': typeof AppChamadosRouteWithChildren
  '/app/equipamentos': typeof AppEquipamentosRouteWithChildren
  '/app/perfil': typeof AppPerfilRoute
  '/etiqueta/$id': typeof EtiquetaIdRoute
  '/lista-clientes/$id': typeof ListaClientesIdRouteWithChildren
  '/lista-clientes/pendentes': typeof ListaClientesPendentesRoute
  '/tecnico/agenda': typeof TecnicoAgendaRoute
  '/tecnico/atendimentos': typeof TecnicoAtendimentosRoute
  '/tecnico/historico': typeof TecnicoHistoricoRoute
  '/tecnico/perfil': typeof TecnicoPerfilRoute
  '/app/': typeof AppIndexRoute
  '/tecnico/': typeof TecnicoIndexRoute
  '/app/chamados/$id': typeof AppChamadosIdRoute
  '/app/chamados/novo': typeof AppChamadosNovoRoute
  '/app/equipamentos/$id': typeof AppEquipamentosIdRoute
  '/app/equipamentos/novo': typeof AppEquipamentosNovoRoute
  '/tecnico/atendimento/$id': typeof TecnicoAtendimentoIdRouteWithChildren
  '/lista-clientes/$id/equipamentos/$equipId': typeof ListaClientesIdEquipamentosEquipIdRouteWithChildren
  '/lista-clientes/$id/equipamentos/novo': typeof ListaClientesIdEquipamentosNovoRoute
  '/tecnico/atendimento/$id/checklist': typeof TecnicoAtendimentoIdChecklistRoute
  '/tecnico/atendimento/$id/registro': typeof TecnicoAtendimentoIdRegistroRoute
  '/lista-clientes/$id/equipamentos/$equipId/finalizar': typeof ListaClientesIdEquipamentosEquipIdFinalizarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atribuicao-tecnicos': typeof AtribuicaoTecnicosRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-cliente': typeof CadastroClienteRoute
  '/cadastro-tecnico': typeof CadastroTecnicoRoute
  '/lista-clientes': typeof ListaClientesRouteWithChildren
  '/lista-tecnicos': typeof ListaTecnicosRoute
  '/login': typeof LoginRoute
  '/pagamento': typeof PagamentoRoute
  '/planos': typeof PlanosRoute
  '/app/chamados': typeof AppChamadosRouteWithChildren
  '/app/equipamentos': typeof AppEquipamentosRouteWithChildren
  '/app/perfil': typeof AppPerfilRoute
  '/etiqueta/$id': typeof EtiquetaIdRoute
  '/lista-clientes/$id': typeof ListaClientesIdRouteWithChildren
  '/lista-clientes/pendentes': typeof ListaClientesPendentesRoute
  '/tecnico/agenda': typeof TecnicoAgendaRoute
  '/tecnico/atendimentos': typeof TecnicoAtendimentosRoute
  '/tecnico/historico': typeof TecnicoHistoricoRoute
  '/tecnico/perfil': typeof TecnicoPerfilRoute
  '/app': typeof AppIndexRoute
  '/tecnico': typeof TecnicoIndexRoute
  '/app/chamados/$id': typeof AppChamadosIdRoute
  '/app/chamados/novo': typeof AppChamadosNovoRoute
  '/app/equipamentos/$id': typeof AppEquipamentosIdRoute
  '/app/equipamentos/novo': typeof AppEquipamentosNovoRoute
  '/tecnico/atendimento/$id': typeof TecnicoAtendimentoIdRouteWithChildren
  '/lista-clientes/$id/equipamentos/$equipId': typeof ListaClientesIdEquipamentosEquipIdRouteWithChildren
  '/lista-clientes/$id/equipamentos/novo': typeof ListaClientesIdEquipamentosNovoRoute
  '/tecnico/atendimento/$id/checklist': typeof TecnicoAtendimentoIdChecklistRoute
  '/tecnico/atendimento/$id/registro': typeof TecnicoAtendimentoIdRegistroRoute
  '/lista-clientes/$id/equipamentos/$equipId/finalizar': typeof ListaClientesIdEquipamentosEquipIdFinalizarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/atribuicao-tecnicos': typeof AtribuicaoTecnicosRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-cliente': typeof CadastroClienteRoute
  '/cadastro-tecnico': typeof CadastroTecnicoRoute
  '/lista-clientes': typeof ListaClientesRouteWithChildren
  '/lista-tecnicos': typeof ListaTecnicosRoute
  '/login': typeof LoginRoute
  '/pagamento': typeof PagamentoRoute
  '/planos': typeof PlanosRoute
  '/tecnico': typeof TecnicoRouteWithChildren
  '/app/chamados': typeof AppChamadosRouteWithChildren
  '/app/equipamentos': typeof AppEquipamentosRouteWithChildren
  '/app/perfil': typeof AppPerfilRoute
  '/etiqueta/$id': typeof EtiquetaIdRoute
  '/lista-clientes/$id': typeof ListaClientesIdRouteWithChildren
  '/lista-clientes/pendentes': typeof ListaClientesPendentesRoute
  '/tecnico/agenda': typeof TecnicoAgendaRoute
  '/tecnico/atendimentos': typeof TecnicoAtendimentosRoute
  '/tecnico/historico': typeof TecnicoHistoricoRoute
  '/tecnico/perfil': typeof TecnicoPerfilRoute
  '/app/': typeof AppIndexRoute
  '/tecnico/': typeof TecnicoIndexRoute
  '/app/chamados/$id': typeof AppChamadosIdRoute
  '/app/chamados/novo': typeof AppChamadosNovoRoute
  '/app/equipamentos/$id': typeof AppEquipamentosIdRoute
  '/app/equipamentos/novo': typeof AppEquipamentosNovoRoute
  '/tecnico/atendimento/$id': typeof TecnicoAtendimentoIdRouteWithChildren
  '/lista-clientes/$id/equipamentos/$equipId': typeof ListaClientesIdEquipamentosEquipIdRouteWithChildren
  '/lista-clientes/$id/equipamentos/novo': typeof ListaClientesIdEquipamentosNovoRoute
  '/tecnico/atendimento/$id/checklist': typeof TecnicoAtendimentoIdChecklistRoute
  '/tecnico/atendimento/$id/registro': typeof TecnicoAtendimentoIdRegistroRoute
  '/lista-clientes/$id/equipamentos/$equipId/finalizar': typeof ListaClientesIdEquipamentosEquipIdFinalizarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/atribuicao-tecnicos'
    | '/cadastro'
    | '/cadastro-cliente'
    | '/cadastro-tecnico'
    | '/lista-clientes'
    | '/lista-tecnicos'
    | '/login'
    | '/pagamento'
    | '/planos'
    | '/tecnico'
    | '/app/chamados'
    | '/app/equipamentos'
    | '/app/perfil'
    | '/etiqueta/$id'
    | '/lista-clientes/$id'
    | '/lista-clientes/pendentes'
    | '/tecnico/agenda'
    | '/tecnico/atendimentos'
    | '/tecnico/historico'
    | '/tecnico/perfil'
    | '/app/'
    | '/tecnico/'
    | '/app/chamados/$id'
    | '/app/chamados/novo'
    | '/app/equipamentos/$id'
    | '/app/equipamentos/novo'
    | '/tecnico/atendimento/$id'
    | '/lista-clientes/$id/equipamentos/$equipId'
    | '/lista-clientes/$id/equipamentos/novo'
    | '/tecnico/atendimento/$id/checklist'
    | '/tecnico/atendimento/$id/registro'
    | '/lista-clientes/$id/equipamentos/$equipId/finalizar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atribuicao-tecnicos'
    | '/cadastro'
    | '/cadastro-cliente'
    | '/cadastro-tecnico'
    | '/lista-clientes'
    | '/lista-tecnicos'
    | '/login'
    | '/pagamento'
    | '/planos'
    | '/app/chamados'
    | '/app/equipamentos'
    | '/app/perfil'
    | '/etiqueta/$id'
    | '/lista-clientes/$id'
    | '/lista-clientes/pendentes'
    | '/tecnico/agenda'
    | '/tecnico/atendimentos'
    | '/tecnico/historico'
    | '/tecnico/perfil'
    | '/app'
    | '/tecnico'
    | '/app/chamados/$id'
    | '/app/chamados/novo'
    | '/app/equipamentos/$id'
    | '/app/equipamentos/novo'
    | '/tecnico/atendimento/$id'
    | '/lista-clientes/$id/equipamentos/$equipId'
    | '/lista-clientes/$id/equipamentos/novo'
    | '/tecnico/atendimento/$id/checklist'
    | '/tecnico/atendimento/$id/registro'
    | '/lista-clientes/$id/equipamentos/$equipId/finalizar'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/atribuicao-tecnicos'
    | '/cadastro'
    | '/cadastro-cliente'
    | '/cadastro-tecnico'
    | '/lista-clientes'
    | '/lista-tecnicos'
    | '/login'
    | '/pagamento'
    | '/planos'
    | '/tecnico'
    | '/app/chamados'
    | '/app/equipamentos'
    | '/app/perfil'
    | '/etiqueta/$id'
    | '/lista-clientes/$id'
    | '/lista-clientes/pendentes'
    | '/tecnico/agenda'
    | '/tecnico/atendimentos'
    | '/tecnico/historico'
    | '/tecnico/perfil'
    | '/app/'
    | '/tecnico/'
    | '/app/chamados/$id'
    | '/app/chamados/novo'
    | '/app/equipamentos/$id'
    | '/app/equipamentos/novo'
    | '/tecnico/atendimento/$id'
    | '/lista-clientes/$id/equipamentos/$equipId'
    | '/lista-clientes/$id/equipamentos/novo'
    | '/tecnico/atendimento/$id/checklist'
    | '/tecnico/atendimento/$id/registro'
    | '/lista-clientes/$id/equipamentos/$equipId/finalizar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AtribuicaoTecnicosRoute: typeof AtribuicaoTecnicosRoute
  CadastroRoute: typeof CadastroRoute
  CadastroClienteRoute: typeof CadastroClienteRoute
  CadastroTecnicoRoute: typeof CadastroTecnicoRoute
  ListaClientesRoute: typeof ListaClientesRouteWithChildren
  ListaTecnicosRoute: typeof ListaTecnicosRoute
  LoginRoute: typeof LoginRoute
  PagamentoRoute: typeof PagamentoRoute
  PlanosRoute: typeof PlanosRoute
  TecnicoRoute: typeof TecnicoRouteWithChildren
  EtiquetaIdRoute: typeof EtiquetaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tecnico': {
      id: '/tecnico'
      path: '/tecnico'
      fullPath: '/tecnico'
      preLoaderRoute: typeof TecnicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista-tecnicos': {
      id: '/lista-tecnicos'
      path: '/lista-tecnicos'
      fullPath: '/lista-tecnicos'
      preLoaderRoute: typeof ListaTecnicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista-clientes': {
      id: '/lista-clientes'
      path: '/lista-clientes'
      fullPath: '/lista-clientes'
      preLoaderRoute: typeof ListaClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-tecnico': {
      id: '/cadastro-tecnico'
      path: '/cadastro-tecnico'
      fullPath: '/cadastro-tecnico'
      preLoaderRoute: typeof CadastroTecnicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-cliente': {
      id: '/cadastro-cliente'
      path: '/cadastro-cliente'
      fullPath: '/cadastro-cliente'
      preLoaderRoute: typeof CadastroClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atribuicao-tecnicos': {
      id: '/atribuicao-tecnicos'
      path: '/atribuicao-tecnicos'
      fullPath: '/atribuicao-tecnicos'
      preLoaderRoute: typeof AtribuicaoTecnicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnico/': {
      id: '/tecnico/'
      path: '/'
      fullPath: '/tecnico/'
      preLoaderRoute: typeof TecnicoIndexRouteImport
      parentRoute: typeof TecnicoRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/tecnico/perfil': {
      id: '/tecnico/perfil'
      path: '/perfil'
      fullPath: '/tecnico/perfil'
      preLoaderRoute: typeof TecnicoPerfilRouteImport
      parentRoute: typeof TecnicoRoute
    }
    '/tecnico/historico': {
      id: '/tecnico/historico'
      path: '/historico'
      fullPath: '/tecnico/historico'
      preLoaderRoute: typeof TecnicoHistoricoRouteImport
      parentRoute: typeof TecnicoRoute
    }
    '/tecnico/atendimentos': {
      id: '/tecnico/atendimentos'
      path: '/atendimentos'
      fullPath: '/tecnico/atendimentos'
      preLoaderRoute: typeof TecnicoAtendimentosRouteImport
      parentRoute: typeof TecnicoRoute
    }
    '/tecnico/agenda': {
      id: '/tecnico/agenda'
      path: '/agenda'
      fullPath: '/tecnico/agenda'
      preLoaderRoute: typeof TecnicoAgendaRouteImport
      parentRoute: typeof TecnicoRoute
    }
    '/lista-clientes/pendentes': {
      id: '/lista-clientes/pendentes'
      path: '/pendentes'
      fullPath: '/lista-clientes/pendentes'
      preLoaderRoute: typeof ListaClientesPendentesRouteImport
      parentRoute: typeof ListaClientesRoute
    }
    '/lista-clientes/$id': {
      id: '/lista-clientes/$id'
      path: '/$id'
      fullPath: '/lista-clientes/$id'
      preLoaderRoute: typeof ListaClientesIdRouteImport
      parentRoute: typeof ListaClientesRoute
    }
    '/etiqueta/$id': {
      id: '/etiqueta/$id'
      path: '/etiqueta/$id'
      fullPath: '/etiqueta/$id'
      preLoaderRoute: typeof EtiquetaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipamentos': {
      id: '/app/equipamentos'
      path: '/equipamentos'
      fullPath: '/app/equipamentos'
      preLoaderRoute: typeof AppEquipamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chamados': {
      id: '/app/chamados'
      path: '/chamados'
      fullPath: '/app/chamados'
      preLoaderRoute: typeof AppChamadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/tecnico/atendimento/$id': {
      id: '/tecnico/atendimento/$id'
      path: '/atendimento/$id'
      fullPath: '/tecnico/atendimento/$id'
      preLoaderRoute: typeof TecnicoAtendimentoIdRouteImport
      parentRoute: typeof TecnicoRoute
    }
    '/app/equipamentos/novo': {
      id: '/app/equipamentos/novo'
      path: '/novo'
      fullPath: '/app/equipamentos/novo'
      preLoaderRoute: typeof AppEquipamentosNovoRouteImport
      parentRoute: typeof AppEquipamentosRoute
    }
    '/app/equipamentos/$id': {
      id: '/app/equipamentos/$id'
      path: '/$id'
      fullPath: '/app/equipamentos/$id'
      preLoaderRoute: typeof AppEquipamentosIdRouteImport
      parentRoute: typeof AppEquipamentosRoute
    }
    '/app/chamados/novo': {
      id: '/app/chamados/novo'
      path: '/novo'
      fullPath: '/app/chamados/novo'
      preLoaderRoute: typeof AppChamadosNovoRouteImport
      parentRoute: typeof AppChamadosRoute
    }
    '/app/chamados/$id': {
      id: '/app/chamados/$id'
      path: '/$id'
      fullPath: '/app/chamados/$id'
      preLoaderRoute: typeof AppChamadosIdRouteImport
      parentRoute: typeof AppChamadosRoute
    }
    '/tecnico/atendimento/$id/registro': {
      id: '/tecnico/atendimento/$id/registro'
      path: '/registro'
      fullPath: '/tecnico/atendimento/$id/registro'
      preLoaderRoute: typeof TecnicoAtendimentoIdRegistroRouteImport
      parentRoute: typeof TecnicoAtendimentoIdRoute
    }
    '/tecnico/atendimento/$id/checklist': {
      id: '/tecnico/atendimento/$id/checklist'
      path: '/checklist'
      fullPath: '/tecnico/atendimento/$id/checklist'
      preLoaderRoute: typeof TecnicoAtendimentoIdChecklistRouteImport
      parentRoute: typeof TecnicoAtendimentoIdRoute
    }
    '/lista-clientes/$id/equipamentos/novo': {
      id: '/lista-clientes/$id/equipamentos/novo'
      path: '/equipamentos/novo'
      fullPath: '/lista-clientes/$id/equipamentos/novo'
      preLoaderRoute: typeof ListaClientesIdEquipamentosNovoRouteImport
      parentRoute: typeof ListaClientesIdRoute
    }
    '/lista-clientes/$id/equipamentos/$equipId': {
      id: '/lista-clientes/$id/equipamentos/$equipId'
      path: '/equipamentos/$equipId'
      fullPath: '/lista-clientes/$id/equipamentos/$equipId'
      preLoaderRoute: typeof ListaClientesIdEquipamentosEquipIdRouteImport
      parentRoute: typeof ListaClientesIdRoute
    }
    '/lista-clientes/$id/equipamentos/$equipId/finalizar': {
      id: '/lista-clientes/$id/equipamentos/$equipId/finalizar'
      path: '/finalizar'
      fullPath: '/lista-clientes/$id/equipamentos/$equipId/finalizar'
      preLoaderRoute: typeof ListaClientesIdEquipamentosEquipIdFinalizarRouteImport
      parentRoute: typeof ListaClientesIdEquipamentosEquipIdRoute
    }
  }
}

interface AppChamadosRouteChildren {
  AppChamadosIdRoute: typeof AppChamadosIdRoute
  AppChamadosNovoRoute: typeof AppChamadosNovoRoute
}

const AppChamadosRouteChildren: AppChamadosRouteChildren = {
  AppChamadosIdRoute: AppChamadosIdRoute,
  AppChamadosNovoRoute: AppChamadosNovoRoute,
}

const AppChamadosRouteWithChildren = AppChamadosRoute._addFileChildren(
  AppChamadosRouteChildren,
)

interface AppEquipamentosRouteChildren {
  AppEquipamentosIdRoute: typeof AppEquipamentosIdRoute
  AppEquipamentosNovoRoute: typeof AppEquipamentosNovoRoute
}

const AppEquipamentosRouteChildren: AppEquipamentosRouteChildren = {
  AppEquipamentosIdRoute: AppEquipamentosIdRoute,
  AppEquipamentosNovoRoute: AppEquipamentosNovoRoute,
}

const AppEquipamentosRouteWithChildren = AppEquipamentosRoute._addFileChildren(
  AppEquipamentosRouteChildren,
)

interface AppRouteChildren {
  AppChamadosRoute: typeof AppChamadosRouteWithChildren
  AppEquipamentosRoute: typeof AppEquipamentosRouteWithChildren
  AppPerfilRoute: typeof AppPerfilRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChamadosRoute: AppChamadosRouteWithChildren,
  AppEquipamentosRoute: AppEquipamentosRouteWithChildren,
  AppPerfilRoute: AppPerfilRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ListaClientesIdEquipamentosEquipIdRouteChildren {
  ListaClientesIdEquipamentosEquipIdFinalizarRoute: typeof ListaClientesIdEquipamentosEquipIdFinalizarRoute
}

const ListaClientesIdEquipamentosEquipIdRouteChildren: ListaClientesIdEquipamentosEquipIdRouteChildren =
  {
    ListaClientesIdEquipamentosEquipIdFinalizarRoute:
      ListaClientesIdEquipamentosEquipIdFinalizarRoute,
  }

const ListaClientesIdEquipamentosEquipIdRouteWithChildren =
  ListaClientesIdEquipamentosEquipIdRoute._addFileChildren(
    ListaClientesIdEquipamentosEquipIdRouteChildren,
  )

interface ListaClientesIdRouteChildren {
  ListaClientesIdEquipamentosEquipIdRoute: typeof ListaClientesIdEquipamentosEquipIdRouteWithChildren
  ListaClientesIdEquipamentosNovoRoute: typeof ListaClientesIdEquipamentosNovoRoute
}

const ListaClientesIdRouteChildren: ListaClientesIdRouteChildren = {
  ListaClientesIdEquipamentosEquipIdRoute:
    ListaClientesIdEquipamentosEquipIdRouteWithChildren,
  ListaClientesIdEquipamentosNovoRoute: ListaClientesIdEquipamentosNovoRoute,
}

const ListaClientesIdRouteWithChildren = ListaClientesIdRoute._addFileChildren(
  ListaClientesIdRouteChildren,
)

interface ListaClientesRouteChildren {
  ListaClientesIdRoute: typeof ListaClientesIdRouteWithChildren
  ListaClientesPendentesRoute: typeof ListaClientesPendentesRoute
}

const ListaClientesRouteChildren: ListaClientesRouteChildren = {
  ListaClientesIdRoute: ListaClientesIdRouteWithChildren,
  ListaClientesPendentesRoute: ListaClientesPendentesRoute,
}

const ListaClientesRouteWithChildren = ListaClientesRoute._addFileChildren(
  ListaClientesRouteChildren,
)

interface TecnicoAtendimentoIdRouteChildren {
  TecnicoAtendimentoIdChecklistRoute: typeof TecnicoAtendimentoIdChecklistRoute
  TecnicoAtendimentoIdRegistroRoute: typeof TecnicoAtendimentoIdRegistroRoute
}

const TecnicoAtendimentoIdRouteChildren: TecnicoAtendimentoIdRouteChildren = {
  TecnicoAtendimentoIdChecklistRoute: TecnicoAtendimentoIdChecklistRoute,
  TecnicoAtendimentoIdRegistroRoute: TecnicoAtendimentoIdRegistroRoute,
}

const TecnicoAtendimentoIdRouteWithChildren =
  TecnicoAtendimentoIdRoute._addFileChildren(TecnicoAtendimentoIdRouteChildren)

interface TecnicoRouteChildren {
  TecnicoAgendaRoute: typeof TecnicoAgendaRoute
  TecnicoAtendimentosRoute: typeof TecnicoAtendimentosRoute
  TecnicoHistoricoRoute: typeof TecnicoHistoricoRoute
  TecnicoPerfilRoute: typeof TecnicoPerfilRoute
  TecnicoIndexRoute: typeof TecnicoIndexRoute
  TecnicoAtendimentoIdRoute: typeof TecnicoAtendimentoIdRouteWithChildren
}

const TecnicoRouteChildren: TecnicoRouteChildren = {
  TecnicoAgendaRoute: TecnicoAgendaRoute,
  TecnicoAtendimentosRoute: TecnicoAtendimentosRoute,
  TecnicoHistoricoRoute: TecnicoHistoricoRoute,
  TecnicoPerfilRoute: TecnicoPerfilRoute,
  TecnicoIndexRoute: TecnicoIndexRoute,
  TecnicoAtendimentoIdRoute: TecnicoAtendimentoIdRouteWithChildren,
}

const TecnicoRouteWithChildren =
  TecnicoRoute._addFileChildren(TecnicoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AtribuicaoTecnicosRoute: AtribuicaoTecnicosRoute,
  CadastroRoute: CadastroRoute,
  CadastroClienteRoute: CadastroClienteRoute,
  CadastroTecnicoRoute: CadastroTecnicoRoute,
  ListaClientesRoute: ListaClientesRouteWithChildren,
  ListaTecnicosRoute: ListaTecnicosRoute,
  LoginRoute: LoginRoute,
  PagamentoRoute: PagamentoRoute,
  PlanosRoute: PlanosRoute,
  TecnicoRoute: TecnicoRouteWithChildren,
  EtiquetaIdRoute: EtiquetaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
